"""
Convert demo_opus JSON files into DemoShowcase.luau.
Places models in a semicircle in front of the spawn point.
"""

import json, os, math

SCRIPT_DIR = os.path.dirname(__file__)
DEMO_DIR = os.path.join(SCRIPT_DIR, "demo_opus")
OUT_PATH = os.path.join(SCRIPT_DIR, "..", "src", "ReplicatedStorage", "Shared", "DemoShowcase.luau")

# Prompts matching generate_demo.py order
PROMPTS = [
    ("creature", "a majestic phoenix with fiery wings spread wide, trailing embers"),
    ("creature", "a tiny mechanical clockwork spider with brass gears and ruby eyes"),
    ("creature", "a massive armored turtle with a miniature castle on its shell"),
    ("creature", "a ghostly jellyfish that glows neon blue and trails long luminous tentacles"),
    ("creature", "a fluffy three-tailed fox with aurora-colored fur"),
    ("creature", "a stone gargoyle perched with wings folded, glowing cracks in its body"),
    ("vehicle", "a steampunk airship with propellers, brass hull, and observation deck"),
    ("vehicle", "a dragon-shaped roller coaster car with flame decals"),
    ("vehicle", "a sleek neon-lit motorcycle with transparent wheels"),
    ("vehicle", "a flying carpet with tassels and intricate golden patterns"),
    ("prop", "a massive enchanted tree with glowing fruit and a door in its trunk"),
    ("prop", "an ancient stone portal with swirling purple energy in its center"),
]

# Layout: semicircle, radius 30 studs, centered at spawn
CENTER = (0, 0, -20)  # slightly in front of spawn, Y=0 (spawner handles ground)
RADIUS = 35
START_ANGLE = -90  # degrees, -90 = left, +90 = right


def lua_string(s: str) -> str:
    s = s.encode("ascii", "replace").decode("ascii")
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def lua_value(v, indent=2) -> str:
    tabs = "\t" * indent
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        if isinstance(v, float) and v == int(v):
            return str(int(v))
        return str(v)
    if isinstance(v, str):
        return lua_string(v)
    if isinstance(v, list):
        if all(isinstance(x, (int, float)) for x in v):
            return "{ " + ", ".join(str(int(x) if isinstance(x, float) and x == int(x) else x) for x in v) + " }"
        items = []
        for item in v:
            items.append(f"{tabs}\t{lua_value(item, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{tabs}}}"
    if isinstance(v, dict):
        items = []
        for k, val in v.items():
            key_str = k if k.isidentifier() else f'["{k}"]'
            items.append(f"{tabs}\t{key_str} = {lua_value(val, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{tabs}}}"
    return str(v)


def main():
    models = []
    for idx, (category, prompt) in enumerate(PROMPTS):
        fname = os.path.join(DEMO_DIR, f"{idx:02d}_{category}.json")
        if os.path.exists(fname):
            try:
                with open(fname) as f:
                    data = json.load(f)
                if data.get("parts"):
                    # Clean name
                    name = data.get("name", prompt[:30])
                    name = name.replace("Origami ", "").replace("origami ", "")
                    data["name"] = name

                    # Calculate position in semicircle
                    n = len(PROMPTS)
                    angle_range = 180  # degrees
                    angle = START_ANGLE + (angle_range / (n - 1)) * idx
                    rad = math.radians(angle)
                    x = CENTER[0] + RADIUS * math.sin(rad)
                    z = CENTER[2] - RADIUS * math.cos(rad)

                    models.append({
                        "modelData": data,
                        "category": category,
                        "position": [round(x, 1), CENTER[1], round(z, 1)],
                        "prompt": prompt,
                    })
                    parts = len(data.get("parts", []))
                    print(f"  OK  #{idx:02d} ({parts:2d} parts) - {name}")
                else:
                    print(f"  EMPTY #{idx:02d} - {prompt[:50]}")
            except Exception as e:
                print(f"  ERR #{idx:02d} - {e}")
        else:
            print(f"  MISS #{idx:02d} - {prompt[:50]}")

    # Generate Luau
    lines = []
    lines.append("-- AUTO-GENERATED by convert_demo.py - do not edit by hand")
    lines.append("local DemoShowcase = {}\n")
    lines.append("DemoShowcase.MODELS = {")

    for m in models:
        lines.append(f"\t{{")
        lines.append(f"\t\tcategory = {lua_string(m['category'])},")
        lines.append(f"\t\tposition = {{ {m['position'][0]}, {m['position'][1]}, {m['position'][2]} }},")
        lines.append(f"\t\tprompt = {lua_string(m['prompt'])},")
        lines.append(f"\t\tmodelData = {lua_value(m['modelData'], 2)},")
        lines.append(f"\t}},")

    lines.append("}\n")
    lines.append("return DemoShowcase")

    content = "\n".join(lines) + "\n"
    with open(OUT_PATH, "w", newline="\n") as f:
        f.write(content)

    size = os.path.getsize(OUT_PATH)
    print(f"\nGenerated: {OUT_PATH}")
    print(f"  Models: {len(models)} / {len(PROMPTS)}")
    print(f"  File size: {size:,} bytes")


if __name__ == "__main__":
    main()
