"""
Convert demo_grid JSON files into CompetitionData.luau for the in-game grid.
Layout: rows = prompts, columns = 3 models (cheapest to most expensive).
"""

import json, os

SCRIPT_DIR = os.path.dirname(__file__)
GRID_DIR = os.path.join(SCRIPT_DIR, "demo_grid")
OUT_PATH = os.path.join(SCRIPT_DIR, "..", "src", "ReplicatedStorage", "Shared", "CompetitionData.luau")

MODELS = ["flash25_lite", "flash3", "gemini_pro"]
MODEL_DISPLAY = {
    "flash25_lite": "FL 2.5 Lite (~$0.001/gen)",
    "flash3": "Gem 3 Flash (~$0.05/gen)",
    "gemini_pro": "Gem 3.1 Pro (~$0.20/gen)",
}

PROMPTS = [
    {"category": "creature", "prompt": "a giant octopus with eight curling tentacles and glowing eyes"},
    {"category": "creature", "prompt": "a perfectly round pufferfish puffed up with tiny spines all over"},
    {"category": "creature", "prompt": "an enormous sandworm bursting out of the ground, long segmented body"},
    {"category": "creature", "prompt": "a majestic eagle mid-flight with outstretched wings and talons"},
    {"category": "creature", "prompt": "a crystal golem made entirely of jagged translucent shards"},
    {"category": "creature", "prompt": "a tiny ladybug with spotted shell and delicate antennae"},
    {"category": "creature", "prompt": "a long Chinese dragon snaking through the air with whiskers and horns"},
    {"category": "vehicle", "prompt": "a pirate ship with sails and cannons"},
    {"category": "vehicle", "prompt": "a futuristic hoverbike with glowing engine pods"},
    {"category": "vehicle", "prompt": "a hot air balloon with a wicker basket and colorful panels"},
    {"category": "vehicle", "prompt": "a chunky monster truck with oversized wheels"},
    {"category": "vehicle", "prompt": "a wooden rowboat with oars"},
    {"category": "prop", "prompt": "a bubbling cauldron with green potion overflowing"},
    {"category": "prop", "prompt": "a grandfather clock with a swinging pendulum"},
    {"category": "prop", "prompt": "a giant crystal ball on an ornate stand, glowing from within"},
    {"category": "prop", "prompt": "a medieval catapult loaded with a boulder"},
    {"category": "prop", "prompt": "a cozy campfire with a pot hanging over it on a tripod"},
    {"category": "prop", "prompt": "a glowing enchanted blade with a jeweled crossguard"},
    {"category": "prop", "prompt": "a wizard staff with a spiraling crystal at the top"},
    {"category": "prop", "prompt": "a golden trident crackling with energy"},
    {"category": "prop", "prompt": "a massive war hammer with runes etched into the head"},
]


def lua_string(s: str) -> str:
    s = s.encode("ascii", "replace").decode("ascii")
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def lua_value(v, indent=2) -> str:
    tabs = "\t" * indent
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return lua_string(v)
    if isinstance(v, list):
        if all(isinstance(x, (int, float)) for x in v):
            return "{ " + ", ".join(str(x) for x in v) + " }"
        items = []
        for item in v:
            items.append(f"{tabs}\t{lua_value(item, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{tabs}}}"
    if isinstance(v, dict):
        items = []
        for k, val in v.items():
            key_str = k if k.isidentifier() else f'["{k}"]'
            items.append(f"{tabs}\t{key_str} = {lua_value(val, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{tabs}}}"
    return str(v)


def main():
    lines = []
    lines.append("-- AUTO-GENERATED by convert_showcase.py - do not edit by hand")
    lines.append("local CompetitionData = {}\n")

    lines.append("CompetitionData.MODELS = {")
    for m in MODELS:
        lines.append(f'\t"{m}",')
    lines.append("}\n")

    lines.append("CompetitionData.MODEL_DISPLAY = {")
    for k, v in MODEL_DISPLAY.items():
        lines.append(f"\t{k} = {lua_string(v)},")
    lines.append("}\n")

    lines.append('CompetitionData.STYLES = { "freestyle" }\n')

    lines.append("CompetitionData.PROMPTS = {")
    for p in PROMPTS:
        lines.append(f'\t{{ category = "{p["category"]}", prompt = {lua_string(p["prompt"])} }},')
    lines.append("}\n")

    lines.append("CompetitionData.RESULTS = {")
    lines.append("\tfreestyle = {")

    ok_count = 0
    fail_count = 0

    for prompt_idx, prompt_info in enumerate(PROMPTS):
        for model in MODELS:
            fname = os.path.join(GRID_DIR, f"{prompt_idx:02d}_{model}.json")
            key = f"{prompt_idx + 1}_{model}"

            if os.path.exists(fname):
                try:
                    with open(fname) as f:
                        data = json.load(f)
                    if "name" in data:
                        data["name"] = data["name"].replace("Origami ", "").replace("origami ", "")
                    if data.get("parts"):
                        lines.append(f'\t\t["{key}"] = {lua_value(data, 2)},')
                        ok_count += 1
                        continue
                except Exception as e:
                    print(f"  Error reading {fname}: {e}")

            fail_count += 1
            print(f"  Missing: {fname}")

    lines.append("\t},")
    lines.append("}\n")
    lines.append("return CompetitionData")

    content = "\n".join(lines) + "\n"
    with open(OUT_PATH, "w", newline="\n") as f:
        f.write(content)

    size = os.path.getsize(OUT_PATH)
    print(f"\nGenerated: {OUT_PATH}")
    print(f"  Success: {ok_count}")
    print(f"  Missing: {fail_count}")
    print(f"  File size: {size:,} bytes")


if __name__ == "__main__":
    main()
